// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "cep-api/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CEPService is an autogenerated mock type for the CEPService type
type CEPService struct {
	mock.Mock
}

// LookupCEP provides a mock function with given fields: ctx, cep
func (_m *CEPService) LookupCEP(ctx context.Context, cep string) (*model.CEPResult, error) {
	ret := _m.Called(ctx, cep)

	if len(ret) == 0 {
		panic("no return value specified for LookupCEP")
	}

	var r0 *model.CEPResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.CEPResult, error)); ok {
		return rf(ctx, cep)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.CEPResult); ok {
		r0 = rf(ctx, cep)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CEPResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cep)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCEPService creates a new instance of CEPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCEPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CEPService {
	mock := &CEPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
